#!/bin/sh
## This script will copy the `shellnote` executable to /usr/local/bin.

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/shellnote"

install() {
	echo "Copying shellnote to $INSTALL_DIR..."
	cp shellnote $INSTALL_DIR || exit 1
	echo "Installation completed. Type 'shellnote -h' to see available commands."
}

create_config() {
	echo "Copying default config file to $CONF_DIR" 
	mkdir "$CONF_DIR" 
	cp ./shellnote.conf "$CONF_DIR" 
}

while true; do
	echo "This will install shellnote to $INSTALL_DIR. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
   		break
	else
		install 
		create_config
	fi
	break
done
