#!/bin/sh

INSTALL_DIR="/usr/local/bin"
CONF_DIR="/etc/shellnote"
CONF_FILE="shellnote.conf"

install() {
	echo "This will install shellnote to $INSTALL_DIR. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
		echo "Installation cancelled."
   		exit	
	else
		echo "Copying shellnote to $INSTALL_DIR ..."
		cp shellnote "$INSTALL_DIR" || exit 1
		create_config "$CONF_FILE" "$CONF_DIR"
	fi
	echo "Installation completed."
	echo "Type 'shellnote -h' to see available commands."
	exit
}

create_config() {
	echo "Copying default config file to $2/$1 ..." 
	if ! [ -d "$2" ]; then
		mkdir "$2" || exit 1 
	fi
	cp ./"$1" "$2" || exit 1 
}

uninstall() {
	echo "This will completely remove shellnote and its (global) config file."
	echo "Your notes and personal config file will be kept. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
		echo "Uninstallation cancelled."
		exit	
	else
		if [ -e "$INSTALL_DIR/shellnote" ]; then
			rm -f "$INSTALL_DIR/shellnote"
		fi
		if [ -e "$CONF_DIR/$CONF_FILE" ]; then
			rm -f "$CONF_DIR/$CONF_FILE"
			rmdir "$CONF_DIR"
		fi
	fi
	echo "Uninstallation completed."
	exit
	
}

case "$1" in
	"install")
		install;;
	"uninstall")
		uninstall;;
	*)
		echo 'Unknown command. Use "install" or "uninstall".';;
esac
exit
