#!/bin/sh

INSTALL_DIR="/usr/local/bin"
CONF="/etc/shellnote.conf"

install() {
	echo "This will install shellnote to $INSTALL_DIR. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ]; then
		echo "Installation cancelled."
   		exit	
	else
		echo "Installing shellnote to $INSTALL_DIR ..."
		cp shellnote "$INSTALL_DIR" || exit 1
		create_config "$CONF"
	fi
	echo "Installation completed."
	echo "Type 'shellnote -h' to see available commands."
	exit
}

create_config() {
	echo "Copying default config file to $1 ..." 
	cp ./shellnote.conf "$1" || exit 1 
}

uninstall() {
	echo "This will completely remove shellnote and its (global) config file."
	echo "Your notes and personal config file will be kept. Continue? (Y/n) " 
	read -r ANS
	if [ "$ANS" != "${ANS#[Nn]}" ] ; then
		echo "Uninstallation cancelled."
		exit	
	else
		if [ -e "$INSTALL_DIR/shellnote" ]; then
			rm -f "$INSTALL_DIR/shellnote"
		fi
		if [ -e "$CONF" ]; then
			rm -f "$CONF"
		fi
	fi
	echo "Uninstallation completed."
	exit
	
}

case "$1" in
	"install")
		install;;
	"uninstall")
		uninstall;;
	*)
		echo 'Unknown command. Use "install" or "uninstall".';;
esac
exit
