#!/bin/sh
## shellnote is a shell script that enables quick command line note taking.
## Written by Martin Gustavsson, released under GPLv3 license.

## source config file
if [ -e $HOME/.shellnoterc ]; then 
	source $HOME/.shellnoterc
else
	LOG_DIR=$HOME
	LOG_FILE=shellnote.txt
	TIME_FORMAT='%H:%M'
	DATE_FORMAT='%Y-%m-%d'
	CONFIRM_MSG=true
fi

## check if editor env var exists, otherwise set to vim
EDITOR_=${EDITOR:-vim}

## create log file if it doesn't exist
if [ ! -e $LOG_DIR/$LOG_FILE ]; then
	> $LOG_DIR/$LOG_FILE
fi

## form log file path
LOG_PATH="$LOG_DIR/$LOG_FILE"

## help function
help() {
	printf '%b\n' "shellnote: easy note-taking on the command line.\n\nUsage:\tshellnote -a \"This is a note.\"\n\nOptions:\n -a\t\tAdd a new entry\n -e\t\tEdit current entries in external editor\n -d\t\tDelete last entry\n -h\t\tPrint this help\n -p\t\tPrint the last 20 entries\n -P\t\tPrint all entries\n -f\t\tPrint the last 20 entries with space between lines\n -s\t\tSearch entries (supports regex)\n"
}

## create time stamp
DATE=`date +$DATE_FORMAT`
TIME=`date +$TIME_FORMAT`
DATETIME="$DATE\t$TIME"

while getopts ":a:s:dehpPf" OPT ; do
	case $OPT in
		a)
		## add line to end of file
		#VALUES="$@"
		VALUES="$OPTARG"
		ENTRY="$DATETIME\t$VALUES"
		printf '%b\n' "$ENTRY" >> $LOG_PATH
		if [ "$CONFIRM_MSG" = true ]; then
			echo "Added entry to $LOG_PATH."
		fi;;

		s)
		## search log file
		printf "%b" "Search result for \"$OPTARG\":\n\n"
		awk -v STR="$OPTARG" -F '\t' '{if ($3 ~ STR) print $0;}' $LOG_PATH
		;;

		d)
		## delete last line in log file
		sed -i '$d' $LOG_PATH;;

		e)
		## edit with user set editor
		$EDITOR_ $LOG_PATH;;

		h)
		## print help
		help;;
		
		p)
		## print last 20 entries
		#cat -n $LOG_DIR/$LOG_FILE | tail -n 20 # with line numbers
		tail -n 20 $LOG_PATH
		;;

		P)
		## print all entries
		pr -t $LOG_PATH;;

		f)
		## print last 20 entries with pretty format
		#tail -n 20 $LOG_PATH | awk -F '\t' '{print BOLD$1" "$2RESET":  "$3"\n"}'-v BOLD="\033[1m" RESET="\033[0m"
		tail -n 20 $LOG_PATH | pr -td	
		;;

		\?)
		## print if unknown option supplied
		echo "Invalid option: -$OPTARG" 
		help
		exit 1;;

		:)
		## print if no option arguments supplied
		echo "Option -$OPTARG requires an argument."
		exit 1;;
	esac
done
