#!/bin/sh
## shellnote is a shell script that enables quick command line note taking.
## Written by Martin Gustavsson, released under GPLv3 license.

## source config file
if [ -e $HOME/.shellnoterc ]; then 
	source $HOME/.shellnoterc
else
	LOG_DIR=$HOME
	LOG_FILE=shellnote.txt
	CONFIRM=true
	TIME_FORMAT='%H:%M'
	DATE_FORMAT='%Y-%m-%d'
	PRETTY_PRINT=true
fi

## create log file if it doesn't exist
if [ ! -e $LOG_DIR/$LOG_FILE ]; then
	> $LOG_DIR/$LOG_FILE
fi

## help function
help() {
	echo -e "shellnote: easy note-taking on the command line.\n\nUsage:\tshellnote -a \"This is a note.\"\n\nOptions:\n -a\t\tAdd a new entry\n -e\t\tEdit current entries in external editor\n -d\t\tDelete last entry\n -h\t\tPrint this help\n -p\t\tPrint the last 20 entries"
}

## create time stamp
DATE=`date +$DATE_FORMAT`
TIME=`date +$TIME_FORMAT`
DATETIME="$DATE\t$TIME"

while getopts ":a:dehp" OPT ; do
	case $OPT in
		a)
		## add line to end of file
		ENTRY="$DATETIME\t$OPTARG"
		echo -e  $ENTRY >> $LOG_DIR/$LOG_FILE
		if [ "$CONFIRM" = true ]; then
			#echo "Added entry to $LOG_DIR/$LOG_FILE: $OPTARG"
			echo "Added entry to $LOG_DIR/$LOG_FILE."
		fi;;

		d)
		## delete last line in log file
		sed -i '$d' $LOG_DIR/$LOG_FILE;;

		e)
		## edit with user set editor
		$EDITOR $LOG_DIR/$LOG_FILE;;

		h)
		## print help
		help;;
		
		p)
		## print last 20 lines of log file
		#cat -n $LOG_DIR/$LOG_FILE | tail -n 20;;
		if [ "$PRETTY_PRINT" = true ]; then
			tail -n 20 $LOG_DIR/$LOG_FILE | awk -F '\t' '{print BOLD$1" "$2RESET":  "$3"\n"}'-v BOLD="\033[1m" RESET="\033[0m"
		else
			tail -n 20 $LOG_DIR/$LOG_FILE
		fi
		;;

		\?)
		## print if unknown option supplied
		echo "Invalid option: -$OPTARG" 
		exit 1;;

		:)
		## print if no option arguments supplied
		echo "Option -$OPTARG requires an argument."
		exit 1;;
	esac
done

## add line to beginning of file
#sed -i "1i $time: $@" $LOG_DIR/$LOG_FILE 
